# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mstdn
open_collective: # Replace with a single Open Collective username
ko_fi: mstdn
liberapay: mstdn
custom: ['https://bunq.me/Stuxhost', 'https://paypal.me/stuxOS']
