# These are supported funding model platforms

github: Goldfish-Social
patreon: mstdn
open_collective: # Replace with a single Open Collective username
ko_fi: mstdn
liberapay: mstdn
custom: ['https://bunq.me/Stuxhost', 'https://paypal.me/stuxOS']
